module.exports = {
    purge: {
        content: ['./pages/**/*.js', './components/**/*.js}'],
        safelist: [
            'bg-blue-500',
            'bg-green-500',
            'bg-red-500',
            'bg-yellow-500',
            'bg-purple-500',
            'hover:bg-blue-700',
            'hover:bg-green-700',
            'hover:bg-red-700',
            'hover:bg-yellow-700',
            'hover:bg-purple-700',
            'text-white',
            'text-blue-500',
            'text-green-500',
            'text-red-500',
            'text-yellow-500',
            'text-purple-500',
            'hover:text-blue-700',
            'hover:text-green-700',
            'hover:text-red-700',
            'hover:text-yellow-700',
            'hover:text-purple-700',
            'border-blue-500',
            'border-green-500',
            'border-red-500',
            'border-yellow-500',
            'border-purple-500',
            'hover:border-blue-700',
            'hover:border-green-700',
            'hover:border-red-700',
            'hover:border-yellow-700',
            'hover:border-purple-700',
            'py-2',
            'px-4',
        ],
    },
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
